import { FormEvent,useEffect,useState } from "react";
import { supabase } from "../lib/supabase/client";

export function AdminPage(){
 const [session,setSession]=useState<any>(null),[isAdmin,setIsAdmin]=useState(false),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[msg,setMsg]=useState("");
 const [name,setName]=useState(""),[description,setDescription]=useState(""),[price,setPrice]=useState(""),[categoryId,setCategoryId]=useState(""),[image,setImage]=useState<File|null>(null),[preview,setPreview]=useState(""),[cats,setCats]=useState<any[]>([]);
 useEffect(()=>{if(!supabase)return;supabase.auth.getSession().then(({data})=>setSession(data.session));const {data}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>data.subscription.unsubscribe()},[]);
 useEffect(()=>{if(!supabase||!session)return;supabase.rpc("is_admin").then(({data})=>setIsAdmin(Boolean(data)));supabase.from("categories").select("id,name").order("sort_order").then(({data})=>setCats(data??[]))},[session]);
 async function login(e:FormEvent){e.preventDefault();if(!supabase)return;setMsg("");const {error}=await supabase.auth.signInWithPassword({email,password});if(error)setMsg("E-mail ou senha inválidos.")}
 function choose(file?:File){if(!file)return;if(!["image/jpeg","image/png","image/webp"].includes(file.type)){setMsg("Use JPG, PNG ou WebP.");return}if(file.size>5*1024*1024){setMsg("A foto deve ter no máximo 5 MB.");return}setImage(file);setPreview(URL.createObjectURL(file))}
 async function save(e:FormEvent){e.preventDefault();if(!supabase||!isAdmin)return;setMsg("Salvando...");let image_path:string|null=null;if(image){const ext=image.name.split(".").pop()?.toLowerCase()||"jpg";image_path=`${crypto.randomUUID()}.${ext}`;const {error}=await supabase.storage.from("product-images").upload(image_path,image,{contentType:image.type});if(error){setMsg("Não foi possível enviar a foto.");return}}const {error}=await supabase.from("products").insert({name,description,price:Number(price.replace(",",".")),category_id:Number(categoryId),image_path,fallback_emoji:"🍔",active:true});setMsg(error?"Erro ao cadastrar produto.":"Produto cadastrado com sucesso.");if(!error){setName("");setDescription("");setPrice("");setImage(null);setPreview("")}}
 if(!supabase)return <main className="admin-page"><div className="admin-panel"><h1>Admin</h1><p>Configure o Supabase no .env.local.</p></div></main>;
 if(!session)return <main className="admin-page admin-login-page"><form className="admin-panel admin-login-card" onSubmit={login}><div className="admin-login-icon" aria-hidden="true">🔒</div><p className="eyebrow">Área restrita</p><h1>Entrar no Admin</h1><p className="admin-login-copy">Gerencie produtos, preços e fotos do seu cardápio.</p><label>E-mail<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Senha<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label><button className="primary admin-login-button" type="submit">Entrar no painel</button>{msg&&<p>{msg}</p>}</form></main>;
 if(!isAdmin)return <main className="admin-page admin-login-page"><section className="admin-panel admin-access-card"><div className="admin-access-icon" aria-hidden="true">🔐</div><p className="eyebrow">Área administrativa</p><h1>Acesso restrito</h1><p className="admin-access-copy">Sua conta foi autenticada, mas ainda não possui permissão para administrar este cardápio.</p><div className="admin-access-note"><strong>Conta protegida</strong><span>Somente administradores autorizados podem alterar produtos, preços e fotos.</span></div><button className="admin-secondary-button admin-logout-button" onClick={()=>supabase.auth.signOut()}>Sair da conta</button></section></main>;
 return <main className="admin-page admin-login-page"><form className="admin-panel admin-product-card" onSubmit={save}><div className="admin-head"><div><div className="admin-login-icon" aria-hidden="true">🍔</div><p className="eyebrow">Cardápio</p><h1>Novo produto</h1><p className="admin-login-copy">Cadastre produtos, preços e fotos que aparecerão no cardápio.</p></div><button className="admin-secondary-button" type="button" onClick={()=>supabase.auth.signOut()}>Sair</button></div><label>Nome<input value={name} onChange={e=>setName(e.target.value)} required maxLength={120}/></label><label>Descrição<textarea value={description} onChange={e=>setDescription(e.target.value)} maxLength={500}/></label><div className="admin-row"><label>Preço<input inputMode="decimal" value={price} onChange={e=>setPrice(e.target.value)} required placeholder="29,90"/></label><label>Categoria<select value={categoryId} onChange={e=>setCategoryId(e.target.value)} required><option value="">Selecione</option>{cats.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label></div><label className="photo-upload">Foto do produto<input type="file" accept="image/jpeg,image/png,image/webp" capture="environment" onChange={e=>choose(e.target.files?.[0])}/><span>Tirar foto ou escolher da galeria</span></label>{preview&&<div className="photo-preview"><img src={preview} alt="Prévia do produto"/><small>A foto será centralizada e recortada automaticamente no card.</small></div>}<button className="primary admin-save-button" type="submit">Cadastrar produto</button>{msg&&<p>{msg}</p>}</form></main>
}