import { useEffect, useMemo, useRef, useState } from "react";
import { Facebook, Instagram, MessageCircle } from "lucide-react";
import { Header } from "../components/layout/Header";
import { ProductCard } from "../features/menu/ProductCard";
import { CartDrawer } from "../features/cart/CartDrawer";
import { products as fallbackProducts } from "../data/products";
import { getMenuProducts } from "../features/menu/menu.service";
import { defaultStoreSettings,getStoreSettings } from "../features/store/store.service";
import type { CartItem, Product } from "../types/menu";

export function HomePage(){
 const [products,setProducts]=useState<Product[]>(fallbackProducts); const [store,setStore]=useState(defaultStoreSettings); const [dark,setDark]=useState(true); const heroBurgerRef=useRef<HTMLDivElement>(null); const [cart,setCart]=useState<CartItem[]>([]); const [cartOpen,setCartOpen]=useState(false); const [activeCategory,setActiveCategory]=useState("Destaques"); const categoryRefs=useRef<Record<string,HTMLAnchorElement|null>>({}); const categoryScrollRef=useRef<HTMLDivElement|null>(null);
 useEffect(()=>{const burger=heroBurgerRef.current;if(!burger)return;let ticking=false;let stopTimer=0;const origin=burger.parentElement;const update=()=>{const y=window.scrollY;const rect=origin?.getBoundingClientRect();const startCenter=(rect?.left??0)+(rect?.width??burger.offsetWidth)/2;const x=window.innerWidth/2-startCenter;burger.style.setProperty("--burger-roll-x",x+"px");burger.style.setProperty("--burger-roll-y",y+"px");burger.style.setProperty("--burger-roll-r",(y*.8)+"deg");burger.classList.add("is-scrolling");burger.classList.remove("is-returning");window.clearTimeout(stopTimer);stopTimer=window.setTimeout(()=>{burger.classList.remove("is-scrolling");burger.classList.add("is-returning");burger.style.setProperty("--burger-roll-x","0px");burger.style.setProperty("--burger-roll-y","0px");burger.style.setProperty("--burger-roll-r","0deg");window.setTimeout(()=>burger.classList.remove("is-returning"),520)},180);ticking=false};const onScroll=()=>{if(!ticking){requestAnimationFrame(update);ticking=true}};window.addEventListener("scroll",onScroll,{passive:true});return()=>{window.removeEventListener("scroll",onScroll);window.clearTimeout(stopTimer)}},[]);
  useEffect(()=>{let mounted=true;Promise.all([getMenuProducts(),getStoreSettings()]).then(([menu,settings])=>{if(!mounted)return;if(menu.length)setProducts(menu);setStore(settings)}).catch(()=>{});return()=>{mounted=false}},[]);
 useEffect(()=>{const saved=localStorage.getItem("theme");const next=saved?saved==="dark":matchMedia("(prefers-color-scheme: dark)").matches;setDark(next)},[]);
 useEffect(()=>{document.documentElement.dataset.theme=dark?"dark":"light";localStorage.setItem("theme",dark?"dark":"light")},[dark]);
 const count=useMemo(()=>cart.reduce((s,i)=>s+i.quantity,0),[cart]);
 useEffect(()=>{const el=categoryRefs.current[activeCategory];el?.scrollIntoView({behavior:"smooth",block:"nearest",inline:"center"})},[activeCategory]);
 useEffect(()=>{const scroller=categoryScrollRef.current;if(!scroller||window.innerWidth>760||window.matchMedia("(prefers-reduced-motion: reduce)").matches)return;let raf=0;let last=performance.now();let offset=0;const speed=24;const loop=()=>Math.max(0,scroller.scrollWidth/2);const frame=(now:number)=>{const width=loop();if(width>0){offset=(offset+speed*Math.min(50,now-last)/1000)%width;scroller.scrollLeft=offset}last=now;raf=requestAnimationFrame(frame)};raf=requestAnimationFrame(frame);return()=>cancelAnimationFrame(raf)},[]);
 function updateQuantity(key:string,q:number){setCart(c=>q<=0?c.filter(i=>i.cartKey!==key):c.map(i=>i.cartKey===key?{...i,quantity:Math.min(20,q)}:i))}
 function quickAdd(p:Product){setCart(c=>{const key=`${p.id}::`;const found=c.find(i=>i.cartKey===key);return found?c.map(i=>i.cartKey===key?{...i,quantity:i.quantity+1}:i):[...c,{...p,cartKey:key,quantity:1,selectedAddOns:[]}]})}
 return <main><Header storeName={store.store_name} dark={dark} count={count} onTheme={()=>setDark(v=>!v)} onCart={()=>count>0&&setCartOpen(true)}/>
 <section className="hero"><div className="shell hero-grid"><div className="hero-copy"><span className="pill">🔥 Sabor que chega junto</span><h1>Seu burger favorito, <em>sem complicação.</em></h1><p>Escolha, personalize e envie seu pedido direto para o WhatsApp. Sem cadastro.</p><a className="primary" href="#cardapio">Ver cardápio ↓</a></div><div className="burger-stage"><div ref={heroBurgerRef} className="burger burger-roll">🍔</div></div></div></section>
 <nav className="categories" aria-label="Categorias"><div ref={categoryScrollRef} className="shell category-scroll">{[0,1].flatMap(copy=>[["🔥 Destaques","Destaques","#cardapio"],["🍔 Lanches","Lanches","#cardapio"],["🍟 Porções","Porções","#cardapio"],["🥤 Bebidas","Bebidas","#bebidas"],["🍔 Combo","Combos","#combos"],["🍰 Sobremesas","Sobremesas","#cardapio"]].map(([label,name,target])=><a ref={el=>{if(copy===0)categoryRefs.current[name]=el}} className={activeCategory===name?"active":""} href={target} key={`${copy}-${name}`} onClick={()=>setActiveCategory(name)} aria-hidden={copy===1}>{label}</a>))}</div></nav>
 <section className="shell menu" id="cardapio"><p className="eyebrow">Feitos na hora</p><h2>Mais pedidos</h2><div className="product-grid">{products.filter(p=>p.category!=="Bebidas"&&p.category!=="Combos").map(p=><ProductCard key={p.id} product={p} onOpen={quickAdd} onQuickAdd={quickAdd}/>)}</div><div className="menu-section" id="combos"><p className="eyebrow">Economize no pedido</p><h2>Combos</h2><div className="product-grid">{products.filter(p=>p.category==="Combos").map(p=><ProductCard key={p.id} product={p} onOpen={quickAdd} onQuickAdd={quickAdd}/>)}</div></div><div className="menu-section" id="bebidas"><p className="eyebrow">Para acompanhar</p><h2>Bebidas</h2><div className="product-grid">{products.filter(p=>p.category==="Bebidas").map(p=><ProductCard key={p.id} product={p} onOpen={quickAdd} onQuickAdd={quickAdd}/>)}</div></div></section>
 <footer className="site-footer"><div className="shell footer-inner"><div><a href="#" className="logo footer-logo" aria-label={`Voltar ao início — ${store.store_name}`}>{store.store_name.length>5?<>{store.store_name.slice(0,-5)}<span>{store.store_name.slice(-5)}</span></>:store.store_name}</a><p>{store.address||"Feito na hora. Pedido fácil e direto."}</p>{store.opening_hours&&<p>Horário: {store.opening_hours}</p>}<p className={store.is_open?"store-open":"store-closed"}>{store.is_open?"● Aberto":"● Fechado"}</p></div><nav className="footer-social" aria-label="Redes sociais"><a href={`https://wa.me/${store.whatsapp.replace(/\D/g,"")}`} target="_blank" rel="noopener noreferrer" aria-label="WhatsApp"><MessageCircle aria-hidden="true"/></a>{store.instagram_url&&<a href={store.instagram_url} target="_blank" rel="noopener noreferrer" aria-label="Instagram"><Instagram aria-hidden="true"/></a>}{store.facebook_url&&<a href={store.facebook_url} target="_blank" rel="noopener noreferrer" aria-label="Facebook"><Facebook aria-hidden="true"/></a>}</nav><small className="footer-bottom">© {new Date().getFullYear()} {store.store_name} <span aria-hidden="true">·</span> <a href="/admin" className="footer-admin-link">Área do estabelecimento</a></small></div></footer>
 {cartOpen&&count>0&&<CartDrawer items={cart} storeName={store.store_name} whatsapp={store.whatsapp} onClose={()=>setCartOpen(false)} onQuantity={updateQuantity} onClear={()=>{setCart([]);setCartOpen(false)}}/>}
 {count>0&&<button className="cart-bar" onClick={()=>setCartOpen(true)}><span><b>{count}</b> {count===1?"item":"itens"}</span><strong>Ver carrinho →</strong></button>}
 </main>
}
