import { useMemo,useState } from "react";
import type { CartItem } from "../../types/menu";
type Props={items:CartItem[];onClose:()=>void;onQuantity:(key:string,q:number)=>void;onClear:()=>void};
const WHATSAPP_NUMBER=import.meta.env.VITE_WHATSAPP_NUMBER||"5535988953079";
export function CartDrawer({items,onClose,onQuantity,onClear}:Props){
 const [fulfillment,setFulfillment]=useState<"delivery"|"pickup">("pickup"),[customerName,setCustomerName]=useState(""),[address,setAddress]=useState(""),[payment,setPayment]=useState(""),[orderNotes,setOrderNotes]=useState("");
 const total=useMemo(()=>items.reduce((sum,item)=>sum+(item.price+item.selectedAddOns.reduce((s,a)=>s+a.price,0))*item.quantity,0),[items]);
 function finishOrder(){if(!customerName.trim()){alert("Informe seu nome.");return}if(fulfillment==="delivery"&&!address.trim()){alert("Informe o endereço para entrega.");return}if(!payment){alert("Selecione a forma de pagamento.");return}const lines=items.flatMap(item=>{const unit=item.price+item.selectedAddOns.reduce((s,a)=>s+a.price,0);return [`• ${item.quantity}x ${item.name} — R$ ${(unit*item.quantity).toFixed(2).replace(".",",")}`,...item.selectedAddOns.map(a=>`   + ${a.name}`),item.notes?`   Obs.: ${item.notes}`:""].filter(Boolean)});const message=["🍔 *NOVO PEDIDO — BURGER HOUSE*","",`Cliente: ${customerName.trim()}`,`Tipo: ${fulfillment==="delivery"?"Entrega":"Retirada"}`,fulfillment==="delivery"?`Endereço: ${address.trim()}`:"",`Pagamento: ${payment}`,orderNotes.trim()?`Observação: ${orderNotes.trim()}`:"","",...lines,"",`*Total: R$ ${total.toFixed(2).replace(".",",")}*`].join("\n");window.open(`https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(message)}`,"_blank","noopener,noreferrer")}
 return <div className="drawer-backdrop" onMouseDown={onClose}><aside className="cart-drawer" role="dialog" aria-modal="true" aria-labelledby="cart-title" onMouseDown={e=>e.stopPropagation()}>
  <div className="drawer-head"><div><span className="eyebrow">Seu pedido</span><h2 id="cart-title">Carrinho</h2></div><button className="close" onClick={onClose} aria-label="Fechar carrinho">×</button></div>
  <div className="cart-list">{items.map(item=><div className="cart-item" key={item.cartKey}><span className="cart-emoji">{item.emoji}</span><div className="cart-copy"><b>{item.name}</b><small>R$ {(item.price+item.selectedAddOns.reduce((s,a)=>s+a.price,0)).toFixed(2).replace(".",",")}</small></div><div className="qty"><button onClick={()=>onQuantity(item.cartKey,item.quantity-1)}>−</button><b>{item.quantity}</b><button onClick={()=>onQuantity(item.cartKey,item.quantity+1)}>+</button></div></div>)}</div>
  <div className="checkout-details"><div className="fulfillment-toggle"><button className={fulfillment==="pickup"?"active":""} onClick={()=>setFulfillment("pickup")}>Retirada</button><button className={fulfillment==="delivery"?"active":""} onClick={()=>setFulfillment("delivery")}>Entrega</button></div><label>Nome<input value={customerName} onChange={e=>setCustomerName(e.target.value)} placeholder="Seu nome"/></label>{fulfillment==="delivery"&&<label>Endereço<input value={address} onChange={e=>setAddress(e.target.value)} placeholder="Rua, número e bairro"/></label>}<label>Pagamento<select value={payment} onChange={e=>setPayment(e.target.value)}><option value="">Selecione</option><option>Pix</option><option>Dinheiro</option><option>Cartão na entrega</option></select></label><label>Observação<textarea value={orderNotes} onChange={e=>setOrderNotes(e.target.value)} placeholder="Ex.: sem cebola"/></label></div>
  <button className="clear-cart" onClick={onClear}>Limpar carrinho</button>
  <div className="cart-total"><span>Total</span><strong>R$ {total.toFixed(2).replace(".",",")}</strong></div>
  <button className="checkout" onClick={finishOrder}>Finalizar pedido →</button>
 </aside></div>
}
